### ISSUE TITLE
Imported Dashboard shows no data

### ISSUE THREAD

**Issue by hexonMD** [lux4rd0/kidde-collector#2]
<img width="1464" alt="Screenshot 2024-10-18 at 5 33 37 PM" src="https://github.com/user-attachments/assets/e0102e9f-4060-4463-b033-f1a72b1bba28">
I've gone through all the setup steps and can manually see the data for the kiddee devices in grafana but the dashboards I imported from the project don't link to the devices. Is there anything I need to do to the json before importing it? I have it linked to my influxdb

**Comment by lux4rd0** [comment]
Use the drop-down menu on Data Source to select the actual data source you're using for your Kidde data. Because it can't be set before or during the import, you pick it after. Then, you can save the dashboard and choose "Save current variable values as dashboard default."

**Comment by hexonMD** [comment]
I can select my database.. I can also manual query the data source for the different sensor data but it doesn't show in the drop downs under your dashboards. I must be missing something. What query language are you using when you setup the connector in grafana? Flux or SQL?
<img width="751" alt="Screenshot 2024-10-18 at 7 37 22 PM" src="https://github.com/user-attachments/assets/a8a06668-a53e-4ba6-b57d-90b8384530e3">
<img width="851" alt="Screenshot 2024-10-18 at 7 37 10 PM" src="https://github.com/user-attachments/assets/a2f0fac1-3de7-44c2-97f2-05e44599264c">
<img width="904" alt="Screenshot 2024-10-18 at 7 37 07 PM" src="https://github.com/user-attachments/assets/ba946d83-13c9-4391-8883-c05499f76503">

**Comment by lux4rd0** [comment]
The dashboards are using InfluxQL:

https://github.com/lux4rd0/kidde-collector/wiki/Grafana-Datasource

**Comment by hexonMD** [comment]
That solved it! Thanks so much.
